name: Hadolint Check

on: [pull_request, push]

jobs:
  hadolint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: ./Dockerfile
